---
- hosts: runner
  gather_facts: no
  become: no
  vars:
    home_folder: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: set kernel nvr
      set_fact:
        kernel_nvr: "{{ cki_repo_url.strip('/').split('/')[-1] }}"

    - name: show kernel_nvr value
      debug:
        var: kernel_nvr

    - set_fact:
        kernel_folder: "{{ home_folder }}/downloads/{{ kernel_nvr }}"

    - name: create tmp folder to save unarchived file and folder
      file:
        path: "{{ kernel_folder }}"
        state: directory

    - name: download cki kernel artifacts
      get_url:
        url: "{{ cki_repo_url }}/{{ item }}-{{ kernel_nvr }}.rpm"
        dest: "{{ kernel_folder }}"
        validate_certs: no
      with_items:
        - "kernel"
        - "kernel-core"
        - "kernel-modules"
        - "kernel-modules-extra"
