---
- hosts: runner
  gather_facts: no
  become: no

  tasks:
    - name: set kernel nvr
      set_fact:
        kernel_nvr: "{{ cki_repo_url.strip('/').split('/')[-1] }}"

    - name: show kernel_nvr value
      debug:
        var: kernel_nvr

    - name: add guest kernel_nvr into guest group
      ini_file:
        path: "inventory"
        section: guest:vars
        option: kernel_nvr
        value: "{{ kernel_nvr }}"
        no_extra_spaces: yes

    - name: create tmp folder to save unarchived file and folder
      file:
        path: "{{ playbook_dir }}/kernel"
        state: directory

    - name: download cki kernel artifacts
      get_url:
        url: "{{ cki_repo_url }}/{{ item }}-{{ kernel_nvr }}.rpm"
        dest: "{{ playbook_dir }}/kernel"
        validate_certs: no
      with_items:
        - "kernel"
        - "kernel-core"
        - "kernel-modules"
        - "kernel-modules-extra"
